import { test } from "node:test";
import assert from "node:assert/strict";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { CanvasHNLocalSequenceSection } from "./canvas-hn-local-sequence-section";
import { HN_PLACEMENT_EXPLANATION, HN_PLACEMENT_NO_READ, HN_PLACEMENT_UNKNOWN, HN_PLACEMENT_RELOAD, type PlacementPhase } from "./hn-local-canvas-sequence-placement";

test("R26 actual section SSR: exact wording/states and only explicit placement action", () => {
    for (const phase of ["SELECTION_NOT_ELIGIBLE", "NOT_CONFIRMED_PLACED", "PLACING", "PLACED_CURRENT_SESSION", "PLACEMENT_OUTCOME_UNKNOWN", "PLACEMENT_RELOADED_UNVERIFIED", "ERROR"] as PlacementPhase[]) {
        const html = renderToStaticMarkup(createElement(CanvasHNLocalSequenceSection, { entry: { phase, running: phase === "PLACING", inspection: 0 }, blocked: false, selectionReloaded: true, onPlace: () => assert.fail("SSR mutation") }));
        assert.ok(html.includes(HN_PLACEMENT_EXPLANATION)); assert.ok(html.includes(HN_PLACEMENT_NO_READ)); assert.ok(html.includes("加入主序列")); assert.ok(html.includes(`data-hn-placement-state="${phase}"`));
        if (["SELECTION_NOT_ELIGIBLE", "PLACING", "PLACED_CURRENT_SESSION", "PLACEMENT_OUTCOME_UNKNOWN", "PLACEMENT_RELOADED_UNVERIFIED"].includes(phase)) assert.ok(html.includes('disabled=""'));
        if (phase === "PLACEMENT_OUTCOME_UNKNOWN") assert.ok(html.includes(HN_PLACEMENT_UNKNOWN)); if (phase === "PLACEMENT_RELOADED_UNVERIFIED") assert.ok(html.includes(HN_PLACEMENT_RELOAD));
        assert.equal(/重新发送|清除屏障|导出按钮|当前序列总数/.test(html), false);
    }
    const element = CanvasHNLocalSequenceSection({ entry: { phase: "NOT_CONFIRMED_PLACED", running: false, inspection: 0 }, blocked: false, selectionReloaded: false, onPlace: () => {} }); assert.equal(element.type, "section");
});

// R31 additive tests; prior placement tests remain byte-preserved.
import { after } from "node:test";
import { writeFileSync } from "node:fs";
import { CanvasHNLocalReorderSection, type ReorderSectionProps } from "./canvas-hn-local-sequence-section";
import { HN_REORDER_CONFIRMATION, HN_REORDER_CONTINUATION } from "./hn-local-canvas-sequence-reorder";
import { reorderFixture } from "./hn-local-canvas-sequence-reorder.test";
const r31Fixtures: unknown[] = [];
function reorderProps(f: ReturnType<typeof reorderFixture>): ReorderSectionProps { return { entry:f.entry(),canSubmit:f.controller.canSubmit(f.project),onLoad:()=>{void f.load();},onRefresh:()=>{void f.controller.refresh(f.project);},onMove:(id,delta)=>f.controller.move(f.project,id,delta),onSubmit:()=>{void f.submit();},onLookup:intent=>{void f.controller.lookup(f.project,intent);},onContinue:intent=>{void f.controller.continueSame(f.project,intent,async()=>true);} }; }
function reorderButtons(node:unknown): {children?:unknown;onClick?:()=>void;disabled?:boolean}[]{if(Array.isArray(node))return node.flatMap(reorderButtons);if(!node||typeof node!=="object")return [];const e=node as {props?:{children?:unknown;onClick?:()=>void;disabled?:boolean}};return [...(e.props?.onClick?[e.props]:[]),...(Array.isArray(e.props?.children)?e.props.children:[e.props?.children]).flatMap(reorderButtons)];}
after(()=>{if(process.env.HN_R31_EVIDENCE)writeFileSync(process.env.HN_R31_EVIDENCE+"-ui.json",JSON.stringify(r31Fixtures,null,2));});
test("R31 initial SSR separate from placement, zero implicit HTTP/write",()=>{const f=reorderFixture();const html=renderToStaticMarkup(<CanvasHNLocalSequenceSection entry={{phase:"SELECTION_NOT_ELIGIBLE",running:false,inspection:0}} blocked selectionReloaded={false} onPlace={()=>assert.fail("SSR cannot place")} reorder={reorderProps(f)}/>);for(const text of ['aria-label="本地序列"','aria-label="主序列安全排序"',"加入主序列","加载安全排序","不改变剪辑顺序","不代表 AI/Provider 成功"])assert.ok(html.includes(text));assert.equal(f.counts.discovery,0);assert.equal(f.m.values.size,0);assert.equal(/draggable|拖拽|drag|drop/.test(html),false);r31Fixtures.push({state:"initial",html});});
test("R31 snapshot IDs/revision, up/down boundaries and controlled click",async()=>{const f=reorderFixture();await f.load();const html=renderToStaticMarkup(<CanvasHNLocalReorderSection {...reorderProps(f)}/>);for(const text of ["sequenceRevision：1","SequenceItemID：A","CandidateID：candidate-A","ShotID：shot-A","上移","下移","确认提交排序"])assert.ok(html.includes(text));const controls=reorderButtons(CanvasHNLocalReorderSection(reorderProps(f))),up=controls.filter(c=>c.children==="上移"),down=controls.filter(c=>c.children==="下移");assert.equal(up[0].disabled,true);assert.equal(down[2].disabled,true);assert.equal(up[1].disabled,false);up[1].onClick!();assert.deepEqual(f.entry().draft,["B","A","C"]);assert.equal(f.counts.post,0);assert.equal(reorderButtons(CanvasHNLocalReorderSection(reorderProps(f))).find(c=>c.children==="确认提交排序")?.disabled,false);r31Fixtures.push({state:"snapshot",html},{state:"draft",html:renderToStaticMarkup(<CanvasHNLocalReorderSection {...reorderProps(f)}/>)});});
test("R31 UNKNOWN recovery and historic COMMITTED distinguish current order",async()=>{const f=reorderFixture();await f.load();f.move();f.setPost("drop-after");await f.submit();const html=renderToStaticMarkup(<CanvasHNLocalReorderSection {...reorderProps(f)}/>);for(const text of ["排序结果未确认","检查服务器结果","继续同一次排序操作","NOT_OBSERVED","预期 revision"])assert.ok(html.includes(text));assert.equal(reorderButtons(CanvasHNLocalReorderSection(reorderProps(f))).find(c=>c.children==="确认提交排序")?.disabled,true);f.setCurrent(["C","A","B"],"9");await f.controller.lookup(f.project,f.intent());const known=renderToStaticMarkup(<CanvasHNLocalReorderSection {...reorderProps(f)}/>);for(const text of ["历史排序命令回执","历史 revision 2","序列已发生后续变化","不证明当前顺序"])assert.ok(known.includes(text));r31Fixtures.push({state:"unknown",html},{state:"historical",html:known});});
test("R31 conflict and continuation explicitly distinguish mutation from readonly lookup",async()=>{const f=reorderFixture();await f.load();f.move();f.setCurrent(["C","B","A"],"5");await f.submit();const html=renderToStaticMarkup(<CanvasHNLocalReorderSection {...reorderProps(f)}/>);assert.ok(html.includes("排序冲突，未覆盖较新的状态"));assert.ok(html.includes("没有排序效果"));assert.ok(HN_REORDER_CONFIRMATION.includes("sequenceRevision"));for(const text of ["可能现在修改","不是只读确认","同一个 intent","不会覆盖较新的"])assert.ok(HN_REORDER_CONTINUATION.includes(text),text);r31Fixtures.push({state:"conflict",html});});

test("R31 two unresolved intents display separate lookup and continuation actions",async()=>{const f=reorderFixture();await f.load();f.move();f.setPost("drop-before");await f.submit();const p=reorderProps(f),first=p.entry.records[0];p.entry.records.push({...first,command:{...first.command,reorderIntentId:crypto.randomUUID(),expectedRevision:"7"}});const html=renderToStaticMarkup(<CanvasHNLocalReorderSection {...p}/>);assert.equal((html.match(/检查服务器结果/g)||[]).length,2);assert.equal((html.match(/继续同一次排序操作/g)||[]).length,2);assert.ok(html.includes("revision：7"));let lookup="",continuation="";p.onLookup=id=>{lookup=id;};p.onContinue=id=>{continuation=id;};const controls=reorderButtons(CanvasHNLocalReorderSection(p));controls.filter(x=>x.children==="检查服务器结果")[1].onClick!();controls.filter(x=>x.children==="继续同一次排序操作")[0].onClick!();assert.equal(lookup,p.entry.records[1].command.reorderIntentId);assert.equal(continuation,first.command.reorderIntentId);assert.equal(f.counts.post,1);r31Fixtures.push({state:"multiple-unresolved",html});});
