import { test, after } from "node:test";
import assert from "node:assert/strict";
import { writeFileSync } from "node:fs";
import { readReorderJournal, sealReorderRecord, validReorderRecord, reorderJournalKey, type ReorderJournal, type ReorderJournalRecord } from "./hn-local-sequence-reorder-journal";
import { reorderCanonical, type ReorderCommand, type ReorderReceipt } from "@/services/hn/local-sequence-reorder";
export function record(project = "project", intent = crypto.randomUUID()): ReorderJournalRecord { const now = "2026-10-07T00:00:00.000Z"; return { journalVersion:1,projectId:project,sequenceId:"main",createdAt:now,updatedAt:now,command:{protocolVersion:1,reorderIntentId:intent,expectedRevision:"1",desiredSequenceItemIds:["B","A","C"]},state:"PREPARED",receipt:null }; }
export function memoryJournal() { const values=new Map<string,unknown>(), events:string[]=[]; const journal:ReorderJournal={async keys(){events.push("keys");return [...values.keys()];},async getItem(k){events.push("read:"+(values.get(k) as ReorderJournalRecord|null)?.state);return structuredClone(values.get(k)??null);},async setItem(k,v){events.push("write:"+v.state);values.set(k,structuredClone(v));return v;}}; return {values,events,journal}; }
export async function makeReceipt(project:string,c:ReorderCommand,outcome:"COMMITTED"|"CONFLICT"="COMMITTED",observed=c.expectedRevision):Promise<ReorderReceipt>{return {protocolVersion:1,projectId:project,sequenceId:"main",reorderIntentId:c.reorderIntentId,canonicalRequestHash:Buffer.from(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(reorderCanonical(c)))).toString("hex"),expectedRevision:c.expectedRevision,outcome,observedRevision:observed,appliedRevision:outcome==="COMMITTED"?(BigInt(observed)+BigInt(1)).toString():null,desiredSequenceItemIds:[...c.desiredSequenceItemIds],errorClass:outcome==="COMMITTED"?null:observed!==c.expectedRevision?"SEQUENCE_REVISION_CONFLICT":"SEQUENCE_SET_CONFLICT"};}
const evidence:unknown[]=[];
test("R31 journal strict closed project/main/UUID/state/time/command binding",async()=>{const r=record(),k=reorderJournalKey(r.projectId,r.command.reorderIntentId);assert.equal(await validReorderRecord(r,r.projectId,k),true);
 for(const v of [{...r,extra:1},{...r,sequenceId:"other"},{...r,journalVersion:2},{...r,projectId:"foreign"},{...r,createdAt:"2026-02-30T00:00:00.000Z"},{...r,updatedAt:"2025-10-07T00:00:00.000Z"},{...r,state:"READY"},{...r,receipt:{}},{...r,command:{...r.command,reorderIntentId:"bad"}},{...r,command:{...r.command,desiredSequenceItemIds:["A","A"]}},{...r,command:{...r.command,extra:1}},{...r,state:"COMMITTED",receipt:undefined}])assert.equal(await validReorderRecord(v,r.projectId,k),false);
 assert.equal(await validReorderRecord(r,"other",k),false);assert.equal(await validReorderRecord(r,r.projectId,k+"x"),false);evidence.push({scenario:"closed-shape-binding",pass:true});});
test("R31 per-intent keys preserve multiple unresolved and project isolation on JSON reopen",async()=>{const m=memoryJournal(),a={...record(),state:"DISPATCHING" as const},b={...record(),state:"UNKNOWN" as const},foreign=record("other");for(const r of [a,b,foreign])await sealReorderRecord(m.journal,r);assert.notEqual(reorderJournalKey(a.projectId,a.command.reorderIntentId),reorderJournalKey(b.projectId,b.command.reorderIntentId));const reopened=new Map<string,unknown>(JSON.parse(JSON.stringify([...m.values])));const j={...m.journal,keys:async()=>[...reopened.keys()],getItem:async(k:string)=>reopened.get(k)};assert.deepEqual(await readReorderJournal(j,"project"),[a,b].sort((x,y)=>x.command.reorderIntentId.localeCompare(y.command.reorderIntentId)));assert.equal((await readReorderJournal(j,"other")).length,1);evidence.push({scenario:"json-reopen",records:3,isolated:true});});
test("R31 strict readback PREPARED/DISPATCHING and same-key mismatch fail closed",async()=>{for(const state of ["PREPARED","DISPATCHING"] as const){const m=memoryJournal(),r={...record(),state};assert.deepEqual(await sealReorderRecord(m.journal,r),r);await assert.rejects(sealReorderRecord(m.journal,{...r,command:{...r.command,expectedRevision:"2"}}));const corrupt={...m.journal,getItem:async(k:string)=>{const v=structuredClone(m.values.get(k)) as ReorderJournalRecord|undefined;return v?{...v,command:{...v.command,desiredSequenceItemIds:["wrong"]}}:null;}};await assert.rejects(sealReorderRecord(corrupt,r));}const m=memoryJournal();m.values.set(reorderJournalKey("project",crypto.randomUUID()),{});await assert.rejects(readReorderJournal(m.journal,"project"));});
test("R31 exact terminal receipt required; immutable terminal history",async()=>{const m=memoryJournal(),r=record();for(const state of ["COMMITTED","CONFLICT"] as const){const next={...r,command:{...r.command,reorderIntentId:crypto.randomUUID()},state,receipt:null as ReorderReceipt|null};next.receipt=await makeReceipt(r.projectId,next.command,state,state==="CONFLICT"?"9":"1");assert.equal(await validReorderRecord(next,r.projectId,reorderJournalKey(r.projectId,next.command.reorderIntentId)),true);await sealReorderRecord(m.journal,next);await assert.rejects(sealReorderRecord(m.journal,{...next,state:"UNKNOWN",receipt:null}));assert.equal(await validReorderRecord({...next,receipt:{...next.receipt,canonicalRequestHash:"0".repeat(64)}},r.projectId,reorderJournalKey(r.projectId,next.command.reorderIntentId)),false);}evidence.push({scenario:"receipt-exactness",pass:true});});
after(()=>{if(process.env.HN_R31_EVIDENCE)writeFileSync(process.env.HN_R31_EVIDENCE+"-journal.json",JSON.stringify(evidence,null,2));});
