import { test, after } from "node:test";
import assert from "node:assert/strict";
import { writeFileSync } from "node:fs";
import { HNLocalSequenceReorderController } from "./hn-local-canvas-sequence-reorder";
import { reorderJournalKey, type ReorderJournalRecord } from "./hn-local-sequence-reorder-journal";
import { record, memoryJournal, makeReceipt } from "./hn-local-sequence-reorder-journal.test";
import type { ReorderCommand, ReorderReceipt } from "@/services/hn/local-sequence-reorder";
const evidence:unknown[]=[];
export function reorderFixture(size=3){const m=memoryJournal(), project="project",counts={initialize:0,snapshot:0,post:0,lookup:0,discovery:0,uuid:0},posts:ReorderCommand[]=[],receipts=new Map<string,ReorderReceipt>();let ids=Array.from({length:size},(_,i)=>i<3?["A","B","C"][i]:"item-"+i),revision="1",postMode="ok",discoveryFail=false,snapshotFail=false,lookupMode="normal";
 const ok=(data:unknown)=>Response.json({code:0,data,msg:"ok"});
 const request=(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>{const url=String(input);assert.equal(init?.credentials,"omit");assert.equal(init?.redirect,"error");assert.equal(init?.cache,"no-store");assert.ok(init?.signal);
  if(url==="/api/hn/local-endpoint"){counts.discovery++;if(discoveryFail)throw Error("synthetic");return ok({url:"http://127.0.0.1:8085"});}
  assert.equal(new URL(url).hostname,"127.0.0.1");assert.equal((init?.headers as Record<string,string>)["X-HN-Local-Request"],"1");assert.ok(!url.endsWith("/reorder"));
  if(url.endsWith("/initialize")){counts.initialize++;return ok({protocolVersion:1,projectId:project,sequenceId:"main",sequenceRevision:revision});}
  if(url.endsWith("/reorder-snapshot")){counts.snapshot++;if(snapshotFail)throw Error("synthetic");return ok({protocolVersion:1,projectId:project,sequenceId:"main",sequenceRevision:revision,itemsComplete:true,items:ids.map((id,index)=>({sequenceItemId:id,projectId:project,sequenceId:"main",orderIndex:index,candidateId:"candidate-"+id,shotId:"shot-"+id,resultId:"result-"+id,createdAt:"2026-10-07T00:00:00Z",updatedAt:"2026-10-07T00:00:00Z"}))});}
  if(init?.method==="POST"){counts.post++;const c=JSON.parse(String(init.body)) as ReorderCommand;posts.push(c);assert.equal((m.values.get(reorderJournalKey(project,c.reorderIntentId)) as ReorderJournalRecord)?.state,"DISPATCHING");assert.equal(m.events.at(-1),"read:DISPATCHING");m.events.push("actualPOST");if(postMode==="drop-before")throw Error("synthetic");let r=receipts.get(c.reorderIntentId);if(!r){r=await makeReceipt(project,c,revision===c.expectedRevision?"COMMITTED":"CONFLICT",revision);receipts.set(c.reorderIntentId,r);if(r.outcome==="COMMITTED"){ids=[...c.desiredSequenceItemIds];revision=r.appliedRevision!;}}
   if(postMode==="drop-after")throw Error("synthetic response loss");if(postMode==="invalid")return ok({...r,extra:true});return r.outcome==="CONFLICT"?Response.json({code:1,data:r,msg:r.errorClass},{status:409}):ok(r);
  }
  counts.lookup++;if(lookupMode==="error")throw Error("synthetic");const intent=url.split("/").at(-1)!;return ok(lookupMode==="absent"?{protocolVersion:1,projectId:project,sequenceId:"main",reorderIntentId:intent,outcome:"NOT_OBSERVED"}:receipts.get(intent)||{protocolVersion:1,projectId:project,sequenceId:"main",reorderIntentId:intent,outcome:"NOT_OBSERVED"});
 }) as typeof fetch;
 const deps={journal:m.journal,request,uuid:()=>{counts.uuid++;return crypto.randomUUID();}},controller=new HNLocalSequenceReorderController(()=>{},deps);
 return {m,project,counts,posts,receipts,deps,controller,entry:()=>controller.entry(project),load:()=>controller.load(project),move:()=>controller.move(project,"B",-1),submit:(confirm=async()=>true)=>controller.submit(project,confirm),setPost:(v:string)=>postMode=v,setDiscovery:(v:boolean)=>discoveryFail=v,setSnapshot:(v:boolean)=>snapshotFail=v,setLookup:(v:string)=>lookupMode=v,setCurrent:(newIds:string[],r:string)=>{ids=newIds;revision=r;},intent:()=>controller.entry(project).records.at(-1)!.command.reorderIntentId};
}
test("R31 inspect/open/load/local moves/cancel/unchanged draft zero implicit mutation",async()=>{const f=reorderFixture();await f.controller.inspect(f.project);assert.equal(f.counts.discovery,0);assert.equal(f.m.events.some(v=>v.startsWith("write:")),false);await f.load();assert.deepEqual(f.entry().draft,["A","B","C"]);assert.deepEqual([f.counts.initialize,f.counts.snapshot,f.counts.post],[1,1,0]);assert.equal(await f.submit(),false);f.move();assert.deepEqual(f.entry().draft,["B","A","C"]);assert.equal(f.counts.snapshot,1);assert.equal(await f.submit(async()=>false),false);assert.equal(f.counts.uuid,0);assert.equal(f.counts.post,0);assert.equal(f.m.values.size,0);});
test("R31 PREPARED and DISPATCHING storage/readback failures gate actual POST at zero",async()=>{for(const state of ["PREPARED","DISPATCHING"] as const)for(const kind of ["set","readback","mutate-set"]){const f=reorderFixture();await f.load();f.move();const set=f.m.journal.setItem,get=f.m.journal.getItem;let written=false;f.m.journal.setItem=async(k,r)=>{if(r.state===state){written=true;if(kind==="set")throw Error("synthetic");if(kind==="mutate-set")r.command.desiredSequenceItemIds=["tampered"];}return set(k,r);};f.m.journal.getItem=async k=>{const r=await get(k);return kind==="readback"&&written&&r&&((r as ReorderJournalRecord).state===state)?{...(r as ReorderJournalRecord),command:{...(r as ReorderJournalRecord).command,expectedRevision:"9"}}:r;};assert.equal(await f.submit(),false);assert.equal(f.counts.post,0);evidence.push({scenario:state+"-"+kind,post:f.counts.post,state:f.entry().records.at(-1)?.state,storageBlocked:f.entry().storageBlocked});}});
test("R31 one POST only after durable seal, terminal receipt before success; readonly refresh",async()=>{const f=reorderFixture();await f.load();f.move();assert.equal(await f.submit(),true);assert.equal(f.counts.post,1);assert.equal(f.counts.uuid,1);assert.equal(f.entry().records[0].state,"COMMITTED");assert.equal((f.m.values.values().next().value as ReorderJournalRecord).state,"COMMITTED");assert.equal(f.counts.snapshot,2);assert.deepEqual(f.entry().draft,["B","A","C"]);assert.equal(await f.submit(),false);evidence.push({scenario:"success-durability",events:f.m.events,counts:f.counts,record:f.entry().records[0],snapshot:f.entry().snapshot});});
test("R31 CAS conflict seals receipt and resets to fresh snapshot without automatic reapply",async()=>{const f=reorderFixture();await f.load();f.move();f.setCurrent(["C","B","A"],"2");assert.equal(await f.submit(),true);assert.equal(f.counts.post,1);assert.equal(f.entry().records[0].state,"CONFLICT");assert.deepEqual(f.entry().draft,["C","B","A"]);assert.equal(f.controller.canSubmit(f.project),false);evidence.push({scenario:"cas-conflict",record:f.entry().records[0],snapshot:f.entry().snapshot,post:1});});
test("R31 pre-dispatch discovery abort differs from post-dispatch unknown",async()=>{const f=reorderFixture();await f.load();f.move();f.setDiscovery(true);assert.equal(await f.submit(),false);assert.equal(f.counts.post,0);assert.equal(f.entry().records[0].state,"ABORTED_PRE_DISPATCH");f.setDiscovery(false);assert.equal(await f.submit(),true);assert.equal(f.counts.post,1);assert.equal(f.counts.uuid,2);});
test("R31 drop/invalid response and terminal seal loss stay UNKNOWN; no auto retry or new intent",async()=>{for(const mode of ["drop-before","drop-after","invalid","terminal-write","terminal-read"]){const f=reorderFixture();await f.load();f.move();f.setPost(mode.startsWith("terminal")?"ok":mode);const set=f.m.journal.setItem,get=f.m.journal.getItem;f.m.journal.setItem=async(k,r)=>{if(mode==="terminal-write"&&r.state==="COMMITTED")throw Error("synthetic");return set(k,r);};f.m.journal.getItem=async k=>{const r=await get(k);if(mode==="terminal-read"&&(r as ReorderJournalRecord)?.state==="COMMITTED")throw Error("synthetic");return r;};assert.equal(await f.submit(),false);assert.equal(f.counts.post,1);assert.equal(f.entry().records[0].state,"UNKNOWN");assert.equal(await f.submit(),false);assert.equal(f.counts.uuid,1);evidence.push({scenario:mode,counts:f.counts,state:f.entry().records[0].state});}});
test("R31 reload DISPATCHING, NOT_OBSERVED/error stay barrier; exact lookup terminal recovery",async()=>{for(const kind of ["COMMITTED","CONFLICT"] as const){const f=reorderFixture();await f.load();f.move();if(kind==="CONFLICT")f.setCurrent(["C","A","B"],"3");f.setPost("drop-after");await f.submit();const key=reorderJournalKey(f.project,f.intent()),disk=f.m.values.get(key) as ReorderJournalRecord;f.m.values.set(key,{...disk,state:"DISPATCHING"});const reopened=new HNLocalSequenceReorderController(()=>{},f.deps);await reopened.inspect(f.project);assert.equal(reopened.entry(f.project).records[0].state,"DISPATCHING");f.setLookup("absent");assert.equal(await reopened.lookup(f.project,f.intent()),false);f.setLookup("error");assert.equal(await reopened.lookup(f.project,f.intent()),false);f.setLookup("normal");assert.equal(await reopened.lookup(f.project,f.intent()),true);assert.equal(reopened.entry(f.project).records[0].state,kind);assert.equal(f.counts.post,1);}});
test("R31 same-key explicit continuation replay one effect and stale continuation conflict",async()=>{for(const mode of ["drop-before","drop-after","stale"]){const f=reorderFixture();await f.load();f.move();f.setPost(mode==="stale"?"drop-before":mode);await f.submit();const c=structuredClone(f.posts[0]);if(mode==="stale")f.setCurrent(["C","A","B"],"2");f.setPost("ok");assert.equal(await f.controller.continueSame(f.project,f.intent(),async()=>false),false);assert.equal(f.counts.post,1);assert.equal(await f.controller.continueSame(f.project,f.intent(),async command=>{assert.deepEqual(command,c);return true;}),true);assert.deepEqual(f.posts[1],c);assert.equal(f.counts.uuid,1);assert.equal(f.counts.post,2);assert.equal(f.receipts.size,1);assert.equal(f.entry().records[0].state,mode==="stale"?"CONFLICT":"COMMITTED");evidence.push({scenario:"continuation-"+mode,counts:f.counts,posts:f.posts,receipt:f.entry().records[0].receipt});}});
test("R31 multiple unresolved preserve every identity and recovery does not delete another",async()=>{const f=reorderFixture();const a={...record(f.project),state:"UNKNOWN" as const},b={...record(f.project),state:"DISPATCHING" as const};for(const r of [a,b])f.m.values.set(reorderJournalKey(f.project,r.command.reorderIntentId),r);f.receipts.set(a.command.reorderIntentId,await makeReceipt(f.project,a.command));await f.load();f.move();assert.equal(await f.submit(),false);assert.equal(await f.controller.lookup(f.project,a.command.reorderIntentId),true);assert.equal(f.entry().records.length,2);assert.equal(f.entry().records.filter(r=>r.state==="DISPATCHING").length,1);assert.equal(f.controller.canSubmit(f.project),false);assert.equal(f.counts.post,0);evidence.push({scenario:"multi-intent",records:f.entry().records});});
test("R31 historical COMMITTED stays known after later mutation or failed current read",async()=>{const f=reorderFixture();await f.load();f.move();f.setPost("drop-after");await f.submit();f.setCurrent(["C","A","B"],"3");await f.controller.lookup(f.project,f.intent());assert.equal(f.entry().laterChanges,true);assert.deepEqual(f.entry().draft,["C","A","B"]);f.setSnapshot(true);assert.equal(await f.controller.refresh(f.project),false);assert.equal(f.entry().records[0].state,"COMMITTED");assert.equal(f.entry().currentVerified,false);assert.equal(f.counts.post,1);const g=reorderFixture();await g.load();g.move();g.setSnapshot(true);assert.equal(await g.submit(),true);assert.equal(g.entry().records[0].state,"COMMITTED");assert.equal(g.entry().currentVerified,false);});
test("R31 synchronous lock blocks double click during confirm; independent project state",async()=>{const f=reorderFixture();await f.load();f.move();let accept!:(value:boolean)=>void;const waiting=new Promise<boolean>(r=>accept=r),one=f.submit(()=>waiting);assert.equal(f.entry().running,true);assert.equal(await f.submit(),false);assert.equal(f.controller.entry("other").running,false);f.controller.move(f.project,"A",-1);accept(true);await one;assert.equal(f.counts.post,1);const projected=f.entry();projected.draft.push("bad");assert.notDeepEqual(f.entry().draft,projected.draft);});
test("R31 zero/one/256/257-item snapshot bounds and corrupted journal fail closed",async()=>{for(const n of [0,1,256,257]){const f=reorderFixture(n),loaded=await f.load();assert.equal(loaded,n<=256);if(n>1&&n<=256)f.move();assert.equal(f.controller.canSubmit(f.project),n===256);assert.equal(f.counts.post,0);}const f=reorderFixture();f.m.values.set(reorderJournalKey(f.project,crypto.randomUUID()),{broken:true});assert.equal(await f.load(),false);assert.equal(f.entry().storageBlocked,true);assert.equal(f.counts.initialize,0);assert.equal(await f.submit(),false);});
after(()=>{if(process.env.HN_R31_EVIDENCE)writeFileSync(process.env.HN_R31_EVIDENCE+"-controller.json",JSON.stringify(evidence,null,2));});

test("R31 localhost fake HTTP server observes exact POST after seal and one-effect continuation",async()=>{
 const {createServer}=await import("node:http"),f=reorderFixture();let serverPosts=0,serverGets=0,lose=true;
 const server=createServer(async(req,res)=>{try{let body="";for await(const chunk of req)body+=chunk;const path=req.url!;if(req.method==="POST"&&path.endsWith("/reorder-commands"))serverPosts++;else if(req.method==="GET")serverGets++;
 const response=await f.deps.request("http://127.0.0.1:8085"+path,{method:req.method,body:body||undefined,headers:{"X-HN-Local-Request":"1"},credentials:"omit",redirect:"error",cache:"no-store",signal:AbortSignal.timeout(30_000)});res.writeHead(response.status,{"Content-Type":"application/json"});res.end(await response.text());}catch{res.writeHead(500);res.end("{}");}});
 await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address() as import("node:net").AddressInfo,base=`http://127.0.0.1:${address.port}`;
 const request=(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>{if(String(input)==="/api/hn/local-endpoint")return Response.json({code:0,data:{url:base},msg:"ok"});const r=await fetch(input,init);if(lose&&init?.method==="POST"&&String(input).endsWith("/reorder-commands")){lose=false;await r.text();throw Error("synthetic lost response");}return r;}) as typeof fetch;
 const c=new HNLocalSequenceReorderController(()=>{},{...f.deps,request});try{await c.load(f.project);c.move(f.project,"B",-1);assert.equal(await c.submit(f.project,async()=>true),false);assert.equal(serverPosts,1);const intent=c.entry(f.project).records[0].command.reorderIntentId;assert.equal(await c.submit(f.project,async()=>true),false);assert.equal(serverPosts,1);assert.equal(await c.continueSame(f.project,intent,async()=>true),true);assert.equal(serverPosts,2);assert.equal(f.receipts.size,1);assert.deepEqual(f.posts[0],f.posts[1]);assert.equal(c.entry(f.project).records[0].state,"COMMITTED");evidence.push({scenario:"localhost-fake-server",serverPosts,serverGets,serverEffects:f.receipts.size,exactPosts:f.posts});}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
});

test("R31 continuation opaque loss remains unresolved and project switch does not share drafts",async()=>{const f=reorderFixture();await f.load();f.move();f.setPost("drop-before");await f.submit();const command=structuredClone(f.posts[0]);assert.equal(await f.controller.continueSame(f.project,f.intent(),async()=>true),false);assert.equal(f.counts.post,2);assert.equal(f.counts.uuid,1);assert.deepEqual(f.posts[1],command);assert.equal(f.entry().records[0].state,"UNKNOWN");assert.equal(await f.submit(),false);assert.equal(f.controller.entry("other").records.length,0);assert.equal(f.controller.entry("other").snapshot,null);const fresh=new HNLocalSequenceReorderController(()=>{},f.deps);await fresh.inspect(f.project);assert.equal(fresh.entry(f.project).records[0].state,"UNKNOWN");assert.deepEqual(fresh.entry(f.project).records[0].command,command);evidence.push({scenario:"continuation-second-loss-reopen",counts:f.counts,records:fresh.entry(f.project).records});});
