import { describe,test } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
function expect(actual:unknown){return {toBe:(v:unknown)=>assert.equal(actual,v),toEqual:(v:unknown)=>assert.deepEqual(actual,v),toBeDefined:()=>assert.notEqual(actual,undefined),not:{toBe:(v:unknown)=>assert.notEqual(actual,v)},rejects:{toThrow:()=>assert.rejects(actual as Promise<unknown>)}};}
import { initializeExportProtocol,executeExportCommand,lookupExportCommand,verifyExportBundle,exportCanonical,exportCommandHash,validExportCommand,validExportReceipt,validExportStatus,type ExportCommand,type ExportReceipt,type ExportStatus } from "./local-export-commands";
import { mkdir,writeFile } from "node:fs/promises";
const command=():ExportCommand=>({protocolVersion:1,exportIntentId:crypto.randomUUID(),expectedRevision:"3",orderedSequenceItemIds:["item-a","item-b"],format:"hn-offline-bundle-v1"});
const response=(v:unknown,status=200)=>new Response(JSON.stringify({code:0,data:v,msg:"ok"}),{status,headers:{"Content-Type":"application/json"}});
async function receipt(c:ExportCommand):Promise<ExportReceipt>{const exportId=crypto.randomUUID(),base="exports/commands-v1/"+exportId;return {protocolVersion:1,projectId:"test",sequenceId:"main",exportIntentId:c.exportIntentId,canonicalRequestHash:await exportCommandHash(c),expectedRevision:c.expectedRevision,observedRevision:c.expectedRevision,orderedSequenceItemIds:[...c.orderedSequenceItemIds],format:c.format,outcome:"COMMITTED",exportId,bundleRelativePath:base,manifestJsonRelativePath:base+"/ordered-manifest.json",manifestCsvRelativePath:base+"/ordered-manifest.csv",itemCount:c.orderedSequenceItemIds.length,snapshotHash:"b".repeat(64),manifestJsonSHA256:"c".repeat(64),manifestCsvSHA256:"d".repeat(64),commandMarkerSHA256:"e".repeat(64),completedAt:"2026-10-08T00:00:00Z",errorClass:null};}
async function status(c:ExportCommand):Promise<ExportStatus>{const r=await receipt(c);return {protocolVersion:1,projectId:"test",sequenceId:"main",exportIntentId:c.exportIntentId,outcome:"COMMITTED",command:structuredClone(c),canonicalRequestHash:r.canonicalRequestHash,exportId:r.exportId,attemptCount:1,errorClass:null,receipt:r};}
const absent=(c:ExportCommand):ExportStatus=>({protocolVersion:1,projectId:"test",sequenceId:"main",exportIntentId:c.exportIntentId,outcome:"NOT_OBSERVED",command:null,canonicalRequestHash:null,exportId:null,attemptCount:0,errorClass:null,receipt:null});
function injected(data:unknown,inspect?:(url:string,init?:RequestInit)=>void):typeof fetch{return (async (input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);inspect?.(url,init);return url==="/api/hn/local-endpoint"?response({url:"http://127.0.0.1:3018"}):response(data);}) as typeof fetch;}
async function evidence(name:string,data:unknown){const root=process.env.HN_R33_EVIDENCE;if(root){await mkdir(root,{recursive:true});await writeFile(root+"/"+name+".json",JSON.stringify(data,null,2));}}
describe("R33 typed local export protocol",()=>{
 test("canonical request, exact receipt, nullable rejection and safe field shapes",async()=>{const c=command();expect(exportCanonical(c)).toBe('{"expectedRevision":"3","orderedSequenceItemIds":["item-a","item-b"],"format":"hn-offline-bundle-v1"}');const s=await status(c);expect(await validExportStatus(s,"test",c)).toBe(true);expect(await validExportStatus({...s,extra:1},"test",c)).toBe(false);for(const edit of [{outcome:"OTHER"},{expectedRevision:"03"},{observedRevision:3},{exportId:crypto.randomUUID()},{bundleRelativePath:"../escape"},{canonicalRequestHash:"a".repeat(64)},{snapshotHash:null},{itemCount:1},{errorClass:"RAW_UNTRUSTED"},{completedAt:"invalid"}])expect(await validExportReceipt({...s.receipt,...edit},"test",c)).toBe(false);
  for(const edit of [{expectedRevision:3},{expectedRevision:"03"},{expectedRevision:"9223372036854775808"},{protocolVersion:2},{exportIntentId:"AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA"},{orderedSequenceItemIds:["x","x"]},{orderedSequenceItemIds:Array.from({length:257},(_,i)=>"x"+i)},{orderedSequenceItemIds:["../escape"]},{format:"other"},{extra:true}])expect(validExportCommand({...c,...edit})).toBe(false);
  const rejected={...s.receipt,outcome:"REJECTED",observedRevision:"4",errorClass:"SEQUENCE_REVISION_CONFLICT",exportId:null,bundleRelativePath:null,manifestJsonRelativePath:null,manifestCsvRelativePath:null,itemCount:0,snapshotHash:null,manifestJsonSHA256:null,manifestCsvSHA256:null,commandMarkerSHA256:null};expect(await validExportReceipt(rejected,"test",c)).toBe(true);expect(await validExportReceipt({...rejected,observedRevision:"3"},"test",c)).toBe(false);await evidence("typed-canonical",{command:c,canonical:exportCanonical(c),hash:await exportCommandHash(c),receipt:s.receipt,rejected});
 });
 test("immutable capture, exact safe fetch options, one explicit POST",async()=>{const c=command(),original=structuredClone(c),s=await status(c);let posts=0;const seen:unknown[]=[];const request=injected(s,(url,init)=>{expect(init?.credentials).toBe("omit");expect(init?.redirect).toBe("error");expect(init?.cache).toBe("no-store");expect(init?.signal).toBeDefined();if(url==="/api/hn/local-endpoint")c.expectedRevision="9";else{posts++;expect(init?.method).toBe("POST");expect(init?.headers).toEqual({"Content-Type":"application/json","X-HN-Local-Request":"1"});expect(JSON.parse(init?.body as string)).toEqual(original);seen.push({url,method:init?.method,body:JSON.parse(init?.body as string)});}});expect(await executeExportCommand("test",c,request)).toEqual(s);expect(posts).toBe(1);await evidence("typed-fetch-options",{posts,seen,captured:original,credentials:"omit",redirect:"error",cache:"no-store",automaticPostRetry:0});
 });
 test("readonly NOT_OBSERVED and observed nonterminal do not claim success",async()=>{const c=command();expect((await lookupExportCommand("test",c,injected(absent(c)))).outcome).toBe("NOT_OBSERVED");const s=await status(c);const active={...s,outcome:"COPYING",receipt:null};expect(await validExportStatus(active,"test",c)).toBe(true);expect(await validExportStatus({...active,attemptCount:4},"test",c)).toBe(false);expect(await validExportStatus({...absent(c),receipt:s.receipt},"test",c)).toBe(false);
 });
 test("initialize and explicit verification require matching historical receipt",async()=>{const c=command();expect(await initializeExportProtocol("test",injected({protocolVersion:1,projectId:"test",sequenceId:"main"}))).toEqual({protocolVersion:1,projectId:"test",sequenceId:"main"});const s=await status(c);let calls=0;const request=(async (input:RequestInfo|URL,init?:RequestInit)=>{const u=String(input);if(u==="/api/hn/local-endpoint")return response({url:"http://127.0.0.1:3018"});calls++;expect(init?.method).toBe("GET");return u.endsWith("/bundle-verification")?response({protocolVersion:1,projectId:"test",sequenceId:"main",exportIntentId:c.exportIntentId,exportId:s.exportId,health:"CORRUPT"}):response(s);}) as typeof fetch;expect((await verifyExportBundle("test",c,request)).health).toBe("CORRUPT");expect(calls).toBe(2);expect(s.outcome).toBe("COMMITTED");await expect(verifyExportBundle("test",c,injected(absent(c)))).rejects.toThrow();
 });
 test("malformed/truncated/duplicate/oversized/redirected/wrong-target response never retries",async()=>{const c=command(),s=await status(c);const bads=[()=>{const r=response(s);Object.defineProperty(r,"redirected",{value:true});return r;},()=>new Response("{",{headers:{"Content-Type":"application/json"}}),()=>new Response('{"code":0,"code":0,"data":null,"msg":"ok"}',{headers:{"Content-Type":"application/json"}}),()=>new Response("x".repeat(1_048_577),{headers:{"Content-Type":"application/json"}}),()=>response({...s,exportIntentId:crypto.randomUUID()}),()=>response({...s,command:{...c,expectedRevision:"4"}}),()=>response({...s,extra:true}),()=>new Response("{}",{headers:{"Content-Type":"text/plain"}})];
  for(const bad of bads){let posts=0;const request=(async (input:RequestInfo|URL)=>{if(String(input)==="/api/hn/local-endpoint")return response({url:"http://127.0.0.1:3018"});posts++;return bad();}) as typeof fetch;await expect(executeExportCommand("test",c,request)).rejects.toThrow();expect(posts).toBe(1);}
  let calls=0;await expect(executeExportCommand("test",{...c,format:"bad"} as unknown as ExportCommand,injected(s,()=>{calls++;}))).rejects.toThrow();expect(calls).toBe(0);
  await expect(executeExportCommand("test",c,(async ()=>response({url:"https://remote.invalid"})) as typeof fetch)).rejects.toThrow();
 });
 test("actual localhost server counts response-loss, exact lookup, continuation and explicit new intent",async()=>{
  const c=command();const stored=new Map<string,ExportStatus>();let serverPosts=0,effects=0,lose=true;const observed:ExportCommand[]=[];
  const server=createServer(async(req,res)=>{try{let result:Response;if(req.method==="POST"){serverPosts++;const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));const body=JSON.parse(Buffer.concat(chunks).toString()) as ExportCommand;observed.push(body);let s=stored.get(body.exportIntentId);if(s&&exportCanonical(s.command!)!==exportCanonical(body)){result=new Response(JSON.stringify({code:1,data:null,msg:"EXPORT_INTENT_CONFLICT"}),{status:409,headers:{"Content-Type":"application/json"}});}else{if(!s){s=await status(body);stored.set(body.exportIntentId,s);effects++;}if(lose){lose=false;result=new Response("{",{headers:{"Content-Type":"application/json"}});}else result=response(s);}}else{const intent=req.url!.split("/").at(-1)!;result=response(stored.get(intent)??absent({...c,exportIntentId:intent}));}res.writeHead(result.status,Object.fromEntries(result.headers.entries()));res.end(await result.text());}catch{res.writeHead(500);res.end();}});
  await new Promise<void>((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",resolve);});const address=server.address();assert.ok(address&&typeof address!=="string");const port=address.port;
  const request=(async (input:RequestInfo|URL,init?:RequestInit)=>String(input)==="/api/hn/local-endpoint"?response({url:"http://127.0.0.1:"+port}):fetch(input,init)) as typeof fetch;
  try{await expect(executeExportCommand("test",c,request)).rejects.toThrow();expect(serverPosts).toBe(1);expect(effects).toBe(1);const exact=await lookupExportCommand("test",c,request);expect(exact.outcome).toBe("COMMITTED");expect(serverPosts).toBe(1);expect(await executeExportCommand("test",c,request)).toEqual(exact);expect(serverPosts).toBe(2);expect(effects).toBe(1);const different={...c,exportIntentId:crypto.randomUUID()};const next=await executeExportCommand("test",different,request);expect(next.exportId).not.toBe(exact.exportId);expect(serverPosts).toBe(3);expect(effects).toBe(2);await evidence("typed-actual-localhost",{serverPosts,effects,observed,firstRequestResponseBodyLost:true,lookupPosts:0,automaticRetry:0,sameKeyContinuationEffect:1,explicitNewIntentEffect:2});}finally{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));}
 });
});
