import { isHNProjectId, localBackendURL } from "./local-reference";
import { validSequenceRevision } from "./local-sequence-reorder";
export type ExportCommand = { protocolVersion: 1; exportIntentId: string; expectedRevision: string; orderedSequenceItemIds: string[]; format: "hn-offline-bundle-v1" };
export type ExportProtocolState = { protocolVersion: 1; projectId: string; sequenceId: "main" };
export type ExportReceipt = ExportProtocolState & { exportIntentId: string; canonicalRequestHash: string; expectedRevision: string; observedRevision: string; orderedSequenceItemIds: string[]; format: "hn-offline-bundle-v1"; outcome: "COMMITTED" | "REJECTED" | "FAILED"; exportId: string | null; bundleRelativePath: string | null; manifestJsonRelativePath: string | null; manifestCsvRelativePath: string | null; itemCount: number; snapshotHash: string | null; manifestJsonSHA256: string | null; manifestCsvSHA256: string | null; commandMarkerSHA256: string | null; completedAt: string; errorClass: string | null };
export type ExportStatus = ExportProtocolState & { exportIntentId: string; outcome: "NOT_OBSERVED" | "IN_PROGRESS" | "RESERVED" | "COPYING" | "READY_TO_FINALIZE" | "RETRYABLE" | "RECOVERY_BLOCKED" | "COMMITTED" | "REJECTED" | "FAILED"; command: ExportCommand | null; canonicalRequestHash: string | null; exportId: string | null; attemptCount: number; errorClass: string | null; receipt: ExportReceipt | null };
export type ExportBundleHealth = ExportProtocolState & { exportIntentId: string; exportId: string; health: "VERIFIED" | "MISSING" | "CORRUPT" };
const closed = (v: unknown, keys: string[]): v is Record<string, unknown> => !!v && typeof v === "object" && !Array.isArray(v) && Object.keys(v).sort().join(",") === [...keys].sort().join(",");
const uuid = (v: unknown): v is string => typeof v === "string" && /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(v);
const hash = (v: unknown): v is string => typeof v === "string" && /^[a-f0-9]{64}$/.test(v);
const ids = (v: unknown): v is string[] => Array.isArray(v) && v.length <= 256 && v.every(x => typeof x === "string" && isHNProjectId(x)) && new Set(v).size === v.length;
const timestamp = (v: unknown) => typeof v === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/.test(v) && Number.isFinite(Date.parse(v)) && new Date(v).toISOString().slice(0,19) === v.slice(0,19);
const terminal = (s: unknown) => s === "COMMITTED" || s === "REJECTED" || s === "FAILED";
const rejectClasses = ["SEQUENCE_REVISION_CONFLICT","SEQUENCE_VECTOR_CONFLICT","EMPTY_SEQUENCE","READ_CAPACITY_EXCEEDED","EXPORT_OWNERSHIP_REJECTED"];
const activeClasses = ["EXPORT_IO_RETRYABLE","EXPORT_RECOVERY_BLOCKED","EXPORT_ATTEMPT_EXHAUSTED"];
export function validExportCommand(v: unknown): v is ExportCommand { return closed(v,["protocolVersion","exportIntentId","expectedRevision","orderedSequenceItemIds","format"]) && v.protocolVersion === 1 && uuid(v.exportIntentId) && validSequenceRevision(v.expectedRevision) && ids(v.orderedSequenceItemIds) && v.format === "hn-offline-bundle-v1"; }
export const exportCanonical = (c: ExportCommand) => JSON.stringify({ expectedRevision:c.expectedRevision, orderedSequenceItemIds:c.orderedSequenceItemIds, format:c.format });
export async function exportCommandHash(c: ExportCommand) { const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(exportCanonical(c))); return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join(""); }
const receiptKeys = ["protocolVersion","projectId","sequenceId","exportIntentId","canonicalRequestHash","expectedRevision","observedRevision","orderedSequenceItemIds","format","outcome","exportId","bundleRelativePath","manifestJsonRelativePath","manifestCsvRelativePath","itemCount","snapshotHash","manifestJsonSHA256","manifestCsvSHA256","commandMarkerSHA256","completedAt","errorClass"];
export async function validExportReceipt(v: unknown, project: string, c: ExportCommand): Promise<boolean> {
 if (!validExportCommand(c) || !closed(v,receiptKeys) || v.protocolVersion !== 1 || v.projectId !== project || v.sequenceId !== "main" || v.exportIntentId !== c.exportIntentId || v.canonicalRequestHash !== await exportCommandHash(c) || v.expectedRevision !== c.expectedRevision || !validSequenceRevision(v.observedRevision) || !ids(v.orderedSequenceItemIds) || JSON.stringify(v.orderedSequenceItemIds) !== JSON.stringify(c.orderedSequenceItemIds) || v.format !== c.format || !timestamp(v.completedAt) || !Number.isInteger(v.itemCount)) return false;
 if (v.outcome === "REJECTED") return rejectClasses.includes(v.errorClass as string) && v.itemCount === 0 && [v.exportId,v.bundleRelativePath,v.manifestJsonRelativePath,v.manifestCsvRelativePath,v.snapshotHash,v.manifestJsonSHA256,v.manifestCsvSHA256,v.commandMarkerSHA256].every(x=>x === null) && (v.errorClass !== "SEQUENCE_REVISION_CONFLICT" || v.observedRevision !== c.expectedRevision) && (v.errorClass !== "EMPTY_SEQUENCE" || c.orderedSequenceItemIds.length === 0);
 if (!uuid(v.exportId) || !hash(v.snapshotHash) || v.observedRevision !== c.expectedRevision || v.itemCount !== c.orderedSequenceItemIds.length || v.itemCount === 0) return false;
 const base="exports/commands-v1/"+v.exportId;
 if (v.bundleRelativePath !== base || v.manifestJsonRelativePath !== base+"/ordered-manifest.json" || v.manifestCsvRelativePath !== base+"/ordered-manifest.csv") return false;
 if (v.outcome === "FAILED") return v.errorClass === "EXPORT_SOURCE_INTEGRITY" && [v.manifestJsonSHA256,v.manifestCsvSHA256,v.commandMarkerSHA256].every(x=>x === null);
 return v.outcome === "COMMITTED" && v.errorClass === null && hash(v.manifestJsonSHA256) && hash(v.manifestCsvSHA256) && hash(v.commandMarkerSHA256);
}
const statusKeys=["protocolVersion","projectId","sequenceId","exportIntentId","outcome","command","canonicalRequestHash","exportId","attemptCount","errorClass","receipt"];
export async function validExportStatus(v: unknown,project: string,c: ExportCommand): Promise<boolean> {
 if (!closed(v,statusKeys) || v.protocolVersion !== 1 || v.projectId !== project || v.sequenceId !== "main" || v.exportIntentId !== c.exportIntentId || !Number.isInteger(v.attemptCount) || (v.attemptCount as number) < 0 || (v.attemptCount as number)>3) return false;
 if (v.command === null) return (v.outcome === "NOT_OBSERVED" || v.outcome === "IN_PROGRESS") && [v.canonicalRequestHash,v.exportId,v.errorClass,v.receipt].every(x=>x === null) && v.attemptCount === 0;
 if (!validExportCommand(v.command) || v.command.exportIntentId !== c.exportIntentId || exportCanonical(v.command) !== exportCanonical(c) || v.canonicalRequestHash !== await exportCommandHash(c)) return false;
 if (terminal(v.outcome)) return await validExportReceipt(v.receipt,project,c) && closed(v.receipt,receiptKeys) && v.receipt.outcome === v.outcome && v.receipt.exportId === v.exportId && v.receipt.errorClass === v.errorClass && (v.outcome === "REJECTED" ? v.attemptCount === 0 : (v.attemptCount as number)>0);
 return ["RESERVED","COPYING","READY_TO_FINALIZE","RETRYABLE","RECOVERY_BLOCKED","IN_PROGRESS"].includes(v.outcome as string) && v.receipt === null && uuid(v.exportId) && (v.errorClass === null || activeClasses.includes(v.errorClass as string)) && (v.outcome !== "RESERVED" || v.attemptCount === 0) && (!["COPYING","READY_TO_FINALIZE","RETRYABLE"].includes(v.outcome as string) || (v.attemptCount as number)>0);
}
async function boundedJSON(r: Response) {
 if (!r.body || r.redirected || r.headers.get("Content-Type")?.split(";")[0].trim() !== "application/json") throw Error("HN 导出响应无法确认；不会重新发送");
 const reader=r.body.getReader(),chunks:Uint8Array[]=[];let count=0;
 try { while(true){ const {done,value}=await reader.read();if(done)break;count+=value.byteLength;if(count>1_048_576)throw Error("HN 导出响应超出范围");chunks.push(value); } } finally { await reader.cancel().catch(()=>{}); }
 const all=new Uint8Array(count);let offset=0;for(const b of chunks){all.set(b,offset);offset+=b.byteLength;}const text=new TextDecoder("utf-8",{fatal:true}).decode(all),value:unknown=JSON.parse(text); if(JSON.stringify(value)!==text.trim())throw Error("HN 导出响应不是规范闭合 JSON"); return value;
}
async function exchange(project:string,path:string,input:object|undefined,request:typeof fetch,slow=false){
 if(!isHNProjectId(project))throw Error("HN 导出项目无效");const body=input?JSON.stringify(input):undefined;if(body && new TextEncoder().encode(body).byteLength>65_536)throw Error("HN 导出请求超出范围");
 const options={credentials:"omit" as const,redirect:"error" as const,cache:"no-store" as const,signal:AbortSignal.timeout(slow?300_000:30_000)};
 const discovery=await request("/api/hn/local-endpoint",options),found=await boundedJSON(discovery);
 if(discovery.status!==200||!closed(found,["code","data","msg"])||found.code!==0||found.msg!=="ok"||!closed(found.data,["url"])||typeof found.data.url!=="string")throw Error("HN 本机地址无法确认");
 const r=await request(localBackendURL(found.data.url)+"/api/hn/projects/"+encodeURIComponent(project)+"/sequences/main/"+path,{...options,method:input?"POST":"GET",headers:input?{"Content-Type":"application/json","X-HN-Local-Request":"1"}:{"X-HN-Local-Request":"1"},...(body?{body}:{})});
 const v=await boundedJSON(r);if(r.status!==200||!closed(v,["code","data","msg"])||v.code!==0||v.msg!=="ok")throw Error("HN 导出结果无法确认；不会重新发送");return v.data;
}
export async function initializeExportProtocol(project:string,request:typeof fetch=fetch):Promise<ExportProtocolState>{const v=await exchange(project,"export-protocol/initialize",{protocolVersion:1},request);if(!closed(v,["protocolVersion","projectId","sequenceId"])||v.protocolVersion!==1||v.projectId!==project||v.sequenceId!=="main")throw Error("HN 导出协议状态无效");return v as ExportProtocolState;}
export async function executeExportCommand(project:string,command:ExportCommand,request:typeof fetch=fetch):Promise<ExportStatus>{if(!validExportCommand(command))throw Error("HN 导出命令无效");const c=structuredClone(command);const v=await exchange(project,"export-commands",c,request,true);if(!await validExportStatus(v,project,c))throw Error("HN 导出回执不匹配");return v as ExportStatus;}
export async function lookupExportCommand(project:string,command:ExportCommand,request:typeof fetch=fetch):Promise<ExportStatus>{if(!validExportCommand(command))throw Error("HN 导出命令无效");const c=structuredClone(command);const v=await exchange(project,"export-commands/"+encodeURIComponent(c.exportIntentId),undefined,request);if(!await validExportStatus(v,project,c))throw Error("HN 导出回执不匹配");return v as ExportStatus;}
export async function verifyExportBundle(project:string,command:ExportCommand,request:typeof fetch=fetch):Promise<ExportBundleHealth>{if(!validExportCommand(command))throw Error("HN 导出命令无效");const c=structuredClone(command),historical=await lookupExportCommand(project,c,request);if(historical.outcome!=="COMMITTED"||!historical.receipt)throw Error("HN 导出尚未提交");const v=await exchange(project,"export-commands/"+encodeURIComponent(c.exportIntentId)+"/bundle-verification",undefined,request,true);if(!closed(v,["protocolVersion","projectId","sequenceId","exportIntentId","exportId","health"])||v.protocolVersion!==1||v.projectId!==project||v.sequenceId!=="main"||v.exportIntentId!==c.exportIntentId||v.exportId!==historical.receipt.exportId||!["VERIFIED","MISSING","CORRUPT"].includes(v.health as string))throw Error("HN 导出完整性响应无效");return v as ExportBundleHealth;}
